from tkinter import *
from output1 import output
def get_calculator():
    def click(event):
        global val
        text = event.widget.cget("text")
        print(text)
        if text == "=":
            if value.get().isdigit():
                val = int(value.get())
            else:
                val = eval(screen.get())
            value.set(val)
            screen.update()
            output(val)           
        elif text == "C":
            value.set("")
            screen.update()
        else:
            value.set(value.get() + text)
            screen.update()
    root=Tk()
    root.geometry("435x640")
    root.maxsize(width=435,height=640)
    root.minsize(width=435,height=640)
    root.title("Calculator by Navin")
    root.wm_iconbitmap("pic.ico")
    root.config(bg="#E6A4B4")

    value = StringVar()
    value.set("")
    screen = Entry(root,textvariable=value,font="Arial 35 bold",bg="#F5EEE6")
    screen.pack(fill=X,ipady=10)

    f1 = Frame(root,bg="#E6A4B4")
    b1=Button(f1,text="9",font="lucida 35 bold",bg="#FFF8E3")
    b1.pack(side=LEFT,padx=3,pady=3,ipadx=11,ipady=5)
    b1.bind("<Button-1>",click)
    b2=Button(f1,text="8",font="lucida 35 bold",bg="#FFF8E3")
    b2.pack(side=LEFT,padx=3,pady=3,ipadx=11,ipady=5)
    b2.bind("<Button-1>",click)
    b3=Button(f1,text="7",font="lucida 35 bold",bg="#FFF8E3")
    b3.pack(side=LEFT,padx=3,pady=3,ipadx=11,ipady=5)
    b3.bind("<Button-1>",click)
    bdiv=Button(f1,text="/",font="lucida 35 bold",bg="#F3D7CA")
    bdiv.pack(side=LEFT,padx=3,pady=3,ipadx=40,ipady=5)
    bdiv.bind("<Button-1>",click)
    f1.pack(fill=X)

    f2 = Frame(root,bg="#E6A4B4")
    b4=Button(f2,text="6",font="lucida 35 bold",bg="#FFF8E3")
    b4.pack(side=LEFT,padx=3,pady=3,ipadx=11,ipady=5)
    b4.bind("<Button-1>",click)
    b5=Button(f2,text="5",font="lucida 35 bold",bg="#FFF8E3")
    b5.pack(side=LEFT,padx=3,pady=3,ipadx=11,ipady=5)
    b5.bind("<Button-1>",click)
    b6=Button(f2,text="4",font="lucida 35 bold",bg="#FFF8E3")
    b6.pack(side=LEFT,padx=3,pady=3,ipadx=11,ipady=5)
    b6.bind("<Button-1>",click)
    bmul=Button(f2,text="*",font="lucida 35 bold",bg="#F3D7CA")
    bmul.pack(side=LEFT,padx=3,pady=3,ipadx=38,ipady=5)
    bmul.bind("<Button-1>",click)
    f2.pack(fill=X)

    f3 = Frame(root,bg="#E6A4B4")
    b7=Button(f3,text="3",font="lucida 35 bold",bg="#FFF8E3")
    b7.pack(side=LEFT,padx=3,pady=3,ipadx=11,ipady=5)
    b7.bind("<Button-1>",click)
    b8=Button(f3,text="2",font="lucida 35 bold",bg="#FFF8E3")
    b8.pack(side=LEFT,padx=3,pady=3,ipadx=11,ipady=5)
    b8.bind("<Button-1>",click)
    b9=Button(f3,text="1",font="lucida 35 bold",bg="#FFF8E3")
    b9.pack(side=LEFT,padx=3,pady=3,ipadx=11,ipady=5)
    b9.bind("<Button-1>",click)
    bsub=Button(f3,text="-",font="lucida 35 bold",bg="#F3D7CA")
    bsub.pack(side=LEFT,padx=3,pady=3,ipadx=38,ipady=5)
    bsub.bind("<Button-1>",click)
    f3.pack(fill=X)

    f4 = Frame(root,bg="#E6A4B4")
    b0=Button(f4,text="0",font="lucida 35 bold",bg="#FFF8E3")
    b0.pack(side=LEFT,padx=3,pady=3,ipadx=11,ipady=5)
    b0.bind("<Button-1>",click)
    bdot=Button(f4,text=".",font="lucida 35 bold",bg="#FFF8E3")
    bdot.pack(side=LEFT,padx=3,pady=3,ipadx=18,ipady=5)
    bdot.bind("<Button-1>",click)
    bmod=Button(f4,text="%",font="lucida 35 bold",bg="#F3D7CA")
    bmod.pack(side=LEFT,padx=3,pady=3,ipadx=3,ipady=5)
    bmod.bind("<Button-1>",click)
    badd=Button(f4,text="+",font="lucida 35 bold",bg="#F3D7CA")
    badd.pack(side=LEFT,padx=3,pady=3,ipadx=38,ipady=5)
    badd.bind("<Button-1>",click)
    f4.pack(fill=X)

    f5 = Frame(root,bg="#E6A4B4")
    bend=Button(f5,text="C",font="lucida 35 bold",bg="#F0ECE5")
    bend.pack(side=LEFT,padx=3,pady=3,ipadx=40,ipady=5)
    bend.bind("<Button-1>",click)
    bequal=Button(f5,text="=",font="lucida 35 bold",bg="#F0ECE5")
    bequal.pack(side=LEFT,padx=3,pady=3,ipadx=55,ipady=5)
    bequal.bind("<Button-1>",click)
    f5.pack(fill=X)
    root.mainloop()
